format_version = "1.0"

texts = {
  ["audioOutputL"] = "Audio Output",
  ["audioOutputR"] = "Audio Output",
  ["audioInputL"] = "Audio Input",
  ["audioInputR"] = "Audio Input",
  
  ["half_width"] = "Half Width",
  ["n_oscillators"] = "N Oscillators",
  ["scale_factor"] = "Scale Factor",
  ["mix_in"] = "Output mixer",
  ["mix_ex"] = "Output mixer",
  ["mix_pr"] = "Output mixer",
  ["window"] = "Window",
  ["filter_on"] = "Filter on/off",
  ["filter_q"] = "Filter Q",
  ["filter_mode"] = "Filter order",
  ["limiter_on"] = "Limiter on/off",
  ["limiter"] = "Limiter cutoff",
  ["limiter_hs"] = "Limiter hard/soft",
  ["duration_min"] = "Minimum duration",
  ["duration_range"] = "Range of duration",
  ["waveform"] = "Oscillator waveform",
  ["silence"] = "Silence Probability",
  ["silence_on"] = "Silence On",
  ["jitter"] = "Jitter Probability",
  ["jitter_on"] = "Jitter On",
  ["smoothing"] = "Smoothing length",
  ["randomise"] = "Randomise generator",
  
  ["IN"] = "IN",
  ["OUT"] = "OUT",
  ["zero"] = "0",
  ["one"] = "1",
  
  ["triangular"] = "triangular",
  ["rectangular"] = "rectangular",
  ["hamming"] = "hamming",
  ["hanning"] = "hanning",
  ["tanh"] = "tanh",
  ["gaussian"] = "gaussian",
  
  ['sinusoid'] = 'sinusoid',
  ['triangle'] = 'triangle',
  ['square'] = 'square',
  ['sawtooth'] = 'sawtooth',
  ['random']='random',
  ['exponential'] = 'exponential',
  ['step3'] = 'three steps',
  ['step4'] = 'four steps',
  ['stepupdown'] = 'step pyramid',
 
  
  ["short_half_width"] = "width",
  ["short_n_oscillators"] = "nOsc",
  ["short_scale_factor"] = "scale",
  ["short_mix_in"] = "mixin",
  ["short_mix_ex"] = "mixex",
  ["short_mix_pr"] = "mixpr",
  ["short_window"] = "Win",
  ["short_filter_on"] = "LP on",
  ["short_filter_q"] = "Q",
  ["short_filter_mode"] = "order",
  ["short_limiter_on"] = "Lim on",
  ["short_limiter"] = "Lim",
  ["short_limiter_hs"] = "h/s",
  ["short_duration_min"] = "Min d",
  ["short_duration_range"] = "Rng d",
  ["short_waveform"] = "wave",
  ["short_silence"] = "quiet",
  ["short_jitter"]="jitter",
  ["short_smoothing"]="smooth",
  ["short_randomise"]="random",

 
  
  ["shortest_half_width"] = "WID",
  ["shortest_n_oscillators"] = "NOSC",
  ["shortest_scale_factor"] = "SCLE",
  ["shortest_mix_in"] = "MIXI",
  ["shortest_mix_ex"] = "MIXE",
  ["shortest_mix_pr"] = "MIXP",
  ["shortest_window"] = "WIN",
  ["shortest_filter_on"] = "LPON",
  ["shortest_filter_q"] = "Q",
  ["shortest_filter_mode"] = "ORD",
  ["shortest_limiter_on"] = "LION",
  ["shortest_limiter"] = "LI",
  ["shortest_limiter_hs"] = "LIHS",
  ["shortest_duration_min"] = "MIND",
  ["shortest_duration_range"] = "RNGD",
  ["shortest_waveform"] = "WAVE",
  ["shortest_silence"] = "QT",
  ["shortest_jitter"] = "JITT",
  ["shortest_smoothing"] = "SMOT",
  ["shortest_randomise"] = "RND",

  
  ["decibels"] = "^0 dB",
  ["degrees"] = "^0 deg",
  ["volume"] = "volume",
  ["hertz"] = "hz",
  ["osc"] = "oscillators",
  ["scale"] = "^0",
  ["linear_template"] = "^0",
  ["milliseconds"] = "^0 ms",
 
 }